/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const PostInput = IDL.Record({
  'title' : IDL.Text,
  'externalLink' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
});
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'externalLink' : IDL.Opt(IDL.Text),
  'description' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : IDL.Nat,
});

export const idlService = IDL.Service({
  'ageGate' : IDL.Func([IDL.Bool], [], ['query']),
  'createPost' : IDL.Func([PostInput], [], []),
  'deletePost' : IDL.Func([IDL.Nat], [], []),
  'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
  'listPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const PostInput = IDL.Record({
    'title' : IDL.Text,
    'externalLink' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
  });
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'externalLink' : IDL.Opt(IDL.Text),
    'description' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : IDL.Nat,
  });
  
  return IDL.Service({
    'ageGate' : IDL.Func([IDL.Bool], [], ['query']),
    'createPost' : IDL.Func([PostInput], [], []),
    'deletePost' : IDL.Func([IDL.Nat], [], []),
    'getPost' : IDL.Func([IDL.Nat], [Post], ['query']),
    'listPosts' : IDL.Func([IDL.Nat], [IDL.Vec(Post)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };